---
  - name: Create users
    user:
      name: "{{item.name}}"
      state: present
      shell: /bin/aspshell
      generate_ssh_key: yes
      ssh_key_bits: 2048
    with_items:
      - "{{usr}}"
    register: now

  - name: Create the directories 
    file:
      path: "{{item.path}}"
      state: directory
      recurse: yes
    with_items:
      - "{{usr}}"
    when: ansible_hostname == 'sam-aspera-ent1'

  - name: Execute a command
    shell:
#      echo "set_user_data;{{item.item.name}},turner;absolute,{{item.item.path}}" > "/tmp/now-{{item.name}}"
      asconfigurator -x 'set_user_data;user_name,{{item.name}};absolute,{{item.path}}'
    with_items:
      - "{{usr}}"
    when: 
      - ansible_hostname == 'sam-aspera-ent1'
      - now.changed

  - name: Ensure ssh keys are present on Server sam-aspera-ent1
    authorized_key:
      user: "{{item.item.name}}"
      state: present
      #key: "{{ lookup('file', '{{item.key}}') }}"
      key: "{{item.ssh_public_key}}"
    with_items:
      - "{{now.results}}"
    when: ansible_hostname == 'sam-aspera-ent1'

...
